version: '2'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    runtime: nvidia
    restart: unless-stopped

    environment:
      - TZ=America/Detroit
      - PLEX_CLAIM=<claimToken>

    network_mode: host

    volumes:
      - type: bind
        source: /media
        target: /data

      - type: volume
        source: plex_db
        target: /config
        volue:
          nocopy: true

      - type: tmpfs
        target: /transcode

volumes:
  plex_db: