version: '2'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [utility, video]

    restart: unless-stopped

    environment:
      - TZ=America/Detroit
      - HOSTNAME=plex
      - PLEX_CLAIM=claim-6F_g5fXNGN3auGL8uJRF
      - ADVERTISE_IP=http://192.168.1.65:32400

    network_mode: bridge
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"

    volumes:
      - type: bind
        source: /data
        target: /data

      - type: volume
        source: plex_db
        target: /config
        volume:
          nocopy: true

      - type: tmpfs
        target: /transcode

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - WEBUI_PORT=8080

    volumes:
      - type: volume
        source: qbittorrent_config
        target: /config

      - type: bind
        source: /data/torrents
        target: /data/torrents

    network_mode: bridge
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit

    volumes:
      - type: volume
        source: sabnzbd_config
        target: /config
    
    network_mode: bridge
    ports:
      - 8181:8181


  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-movies
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      
    volumes:
      - type: volume
        source: radarr_config
        target: /config

      - type: bind
        source: /data
        target: /data

    network_mode: bridge
    ports:
      - 7878:7878

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit

    volumes:
      - type: volume
        source: prowlarr_config
        target: /config

    network_mode: bridge
    ports:
      - 9696:9696

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"



## Volumes
volumes:
  plex_db:
  qbittorrent_config:
  sabnzbd_config:
  radarr_config:
  prowlarr_config:
  # overseer_config: