version: '2'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    runtime: nvidia
    restart: unless-stopped

    environment:
      - TZ=America/Detroit
      - PLEX_CLAIM=<claimToken>

    network_mode: host
    ports:
    - 32400:32400/tcp

    volumes:
      - type: bind
        source: /data
        target: /data

      - type: volume
        source: plex_db
        target: /config
        volume:
          nocopy: true

      - type: tmpfs
        target: /transcode

## Overseer
  # overseerr:
  #   image: sctx/overseerr
  #   container_name: overseerr
  #   restart: unless-stopped

  #   environment:
  #     - LOG_LEVEL=debug
  #     - TZ=America/Detroit

  #   ports:
  #     - 5055:5055

  #   volumes:
  #     - type: volume
  #       source: overseer_config
  #       target: /app/config
  #       volume:
  #         nocopy: true

## Volumes
volumes:
  plex_db:
  # overseer_config: