version: '2'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    # runtime: nvidia
    restart: unless-stopped

    environment:
      - TZ=America/Detroit
      - HOSTNAME=plex
      - ADVERTISE_IP=http://192.168.1.65:32400
      # - PLEX_CLAIM=<claimToken>

    network_mode: bridge
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"

    volumes:
      - type: bind
        source: /data
        target: /data

      - type: volume
        source: plex_db
        target: /config
        volume:
          nocopy: true

      - type: tmpfs
        target: /transcode

## Overseer
  # overseerr:
  #   image: sctx/overseerr
  #   container_name: overseerr
  #   restart: unless-stopped

  #   environment:
  #     - LOG_LEVEL=debug
  #     - TZ=America/Detroit

  #   ports:
  #     - 5055:5055

  #   volumes:
  #     - type: volume
  #       source: overseer_config
  #       target: /app/config
  #       volume:
  #         nocopy: true

## Volumes
volumes:
  plex_db:
  # overseer_config: